In [1]:
# Python package to read sas, spss and stata files into pandas data frames. It is a wrapper for the C library readstat.
# 
!pip install pyreadstat

Collecting pyreadstat
  Downloading pyreadstat-1.1.5-cp39-cp39-win_amd64.whl (1.4 MB)
Requirement already satisfied: pandas>=1.2.0 in c:\users\sangt\anaconda3\envs\tensorflow\lib\site-packages (from pyreadstat) (1.4.1)
Requirement already satisfied: numpy>=1.18.5 in c:\users\sangt\anaconda3\envs\tensorflow\lib\site-packages (from pandas>=1.2.0->pyreadstat) (1.21.5)
Requirement already satisfied: pytz>=2020.1 in c:\users\sangt\anaconda3\envs\tensorflow\lib\site-packages (from pandas>=1.2.0->pyreadstat) (2021.3)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\sangt\anaconda3\envs\tensorflow\lib\site-packages (from pandas>=1.2.0->pyreadstat) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\users\sangt\anaconda3\envs\tensorflow\lib\site-packages (from python-dateutil>=2.8.1->pandas>=1.2.0->pyreadstat) (1.16.0)
Installing collected packages: pyreadstat
Successfully installed pyreadstat-1.1.5

In [2]:
import pandas as pd

In [4]:
# https://klowf.kwdi.re.kr/portal/dataSet/rdssFileListPage.do? 에서 데이터셋 구하기
# SPSS 파일 (SAV)로 읽기
data1=pd.read_spss("C:\강의자료\BI 및 데이터\klowf_07_p.SAV")
data1.head()

,OPID,Pwave,PwaveA,PwaveB,PDAY,PweiL,PweiC,PweiCA,H01HHID,H02HHID,...,H05DB04,H05DB05,H05DB06,H05DB07,H05DB10,H05DB11,H05FC,H05LE12,H05LE13,H05LE15
0,101.0,7차,기존 응답,7차 기존 응답자,2018-11-06,8473.707425,7191.590725,4451.820241,1.0,1.0,...,아니오,NaN,NaN,아니오,NaN,NaN,조금 어려운 편이다,의료비,교통/통신비,
1,202.0,7차,기존 응답,7차 기존 응답자,2019-04-11,6021.431199,5360.789916,2848.372483,2.0,2.0,...,아니오,NaN,NaN,아니오,NaN,NaN,조금 어려운 편이다,식비(식료품비),교육비,
2,302.0,7차,기존 응답,7차 기존 응답자,2019-03-11,6555.718130,5549.330162,3088.530732,3.0,3.0,...,아니오,NaN,NaN,아니오,NaN,NaN,보통이다,식비(식료품비),없음,
3,402.0,7차,기존 응답,7차 기존 응답자,2019-03-28,1218.705135,1135.059631,967.126734,4.0,4.0,...,아니오,NaN,NaN,아니오,NaN,NaN,여유가 있는 편이다,교육비,교통/통신비,
4,502.0,7차,기존 응답,7차 기존 응답자,2018-11-07,4205.183019,3568.916612,2209.271331,5.0,5.0,...,아니오,NaN,NaN,아니오,NaN,NaN,여유가 있는 편이다,교통/통신비,식비(식료품비),

In [5]:
target1=data1[["Pwave","PwaveB","H05FC","H05LE12","H05LE13"]]
target1.head()

  Pwave     PwaveB       H05FC   H05LE12   H05LE13
0    7차  7차 기존 응답자  조금 어려운 편이다       의료비    교통/통신비
1    7차  7차 기존 응답자  조금 어려운 편이다  식비(식료품비)       교육비
2    7차  7차 기존 응답자        보통이다  식비(식료품비)        없음
3    7차  7차 기존 응답자  여유가 있는 편이다       교육비    교통/통신비
4    7차  7차 기존 응답자  여유가 있는 편이다    교통/통신비  식비(식료품비)

In [6]:
target1.columns=["차수","기존여부","살림살이","1차비용","2차비용"]
target1.head()

   차수       기존여부        살림살이      1차비용      2차비용
0  7차  7차 기존 응답자  조금 어려운 편이다       의료비    교통/통신비
1  7차  7차 기존 응답자  조금 어려운 편이다  식비(식료품비)       교육비
2  7차  7차 기존 응답자        보통이다  식비(식료품비)        없음
3  7차  7차 기존 응답자  여유가 있는 편이다       교육비    교통/통신비
4  7차  7차 기존 응답자  여유가 있는 편이다    교통/통신비  식비(식료품비)

In [7]:
target1.to_csv("target1.csv",index=False)